version: '3'

services:
  app:
    image: klakegg/hugo:0.54.0-ext
    # image: peaceiris/hugo:v0.x.x-mod   # Hugo Modules
    # image: peaceiris/hugo:v0.x.x-full  # Hugo Modules and Node.js
    ports:
      - 1313:1313
      - 3000:3000
    volumes:
      - ${PWD}:/src
    command:
      - server
      - --bind=0.0.0.0
      - --buildDrafts

